name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: nylas/build-dpkg-buster@master
        id: build
        with:
          args: --unsigned-source --unsigned-changes
